export default defineEventHandler((event) => {
    return {
        fsUsertype: "",
        fsTomorrow: "22/02/2021",
        fsUserProduct:
            "https://dwoowoo.freewillsolutions.com/AUTHREF,https://dwoowoo.freewillsolutions.com/BROKREF,https://dSmartsbaws.freewillsolutions.com/SMARTSBA_CA,https://dSmartsbaws.freewillsolutions.com/SMARTSBA_CASH,-",
        fsIpAddress: "10.50.12.130",
        fsRoles:
            "CACHECKER,CAMAKER,CANCELATSCHECKER,CANCELATSMAKER,CMCHECKER,CMMAKER,EXPORTATSCHECKER,EXPORTATSMAKER,ZNCIT",
        fsYesterday: "18/02/2021",
        fsLanguage: "TH",
        fsUserStatus: "A",
        fsUserName: "Nutchayapat  Intaramat (CHECKER)",
        fsSupervisor: 0,
        fsRolename:
            "CACHECKER,CAMAKER,CANCELATSCHECKER,CANCELATSMAKER,CMCHECKER,CMMAKER,EXPORTATSCHECKER,EXPORTATSMAKER,ZNCIT",
        fsSyncos: 0,
        fsOpenwindow: "",
        fsLastLoginDate: "2021-09-02 19:58:56.415",
        fsPassword: "77184BCD1AD98B91",
        fsFirstPage: "frfe100",
        fsSystemDate: "19/02/2021",
        fsHasBeenKicked: false,
        fsSyncsba: 0,
        fsLoginTimestamp: "02/09/2021 20:41:13",
        fsStyles: "amethyst",
        fsUserProject: "AUTHREF,BROKREF,SBA_CA,SBA_CASH,SBA_DELPHI",
        fsDepartment: "",
        fsAuthlevel: "",
        fsKey: "50240dfc-47cc-4946-8cb9-5d95d5e16e31",
        fsImage: "",
        fsUser: "ncit2",
        fsDivision: "DP",
        fsSystem: "",
        fsCenter: 0,
        accessor: "",
        fsBranch: 0,
        fsEmail: "",
        fsIsExpired: false,
        fsUserGroup: "SMART-ADMIN,SMART-SBA",
        fsDate: "02/09/2021",
        fsAdminflag: 0,
        fsUserldap: "",
        fsNewwindowflag: "",
    };
});
